name: storybook_test

on: [push]

jobs:
  storybook_test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      # https://github.com/swc-project/swc/issues/5616
      - name: Install swc
        run: |
          npm install --save-optional \
          "@swc/core-darwin-arm64" \
          "@swc/core-darwin-x64" \
          "@swc/core-linux-arm-gnueabihf" \
          "@swc/core-linux-arm64-gnu" \
          "@swc/core-linux-arm64-musl" \
          "@swc/core-linux-x64-gnu" \
          "@swc/core-linux-x64-musl" \
          "@swc/core-win32-arm64-msvc" \
          "@swc/core-win32-ia32-msvc" \
          "@swc/core-win32-x64-msvc"
      - name: StorybookTest
        uses: ./.github/actions/storybook_test
        with:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_CLIENT_EMAIL: ${{ secrets.GCP_CLIENT_EMAIL }}
          GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
          GCP_PRIVATE_KEY_ID: ${{ secrets.GCP_PRIVATE_KEY_ID }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          DEV_FIRESTORE_COLLECTION: ${{ secrets.DEV_FIRESTORE_COLLECTION }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
